### ISSUE TITLE
UnicodeDecodeError on startup: 'charmap' codec can't decode byte 0x8f

### ISSUE THREAD

**Issue by NightV402** [ColdSpirit0/mod_io_downloader#1]
When I try to run
`python -m mod_io_downloader`
I get this error
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2179: character maps to <undefined>`

**Comment by ColdSpirit0** [comment]
Seems there is something wrong with encoding, but I can't reproduce the issue. I've tried on Windows and Linux. Please provide more information:
- OS
- Python version (run the command python --version)
- Full console output
- Attach the config file, located at Mordhau Dedicated Server\Mordhau\Saved\Config\WindowsServer\Game.ini. It seems there are strange special characters that script cannot read

**Comment by NightV402** [comment]
- OS: **Windows 11 Home**
- Python version: **Python 3.12.3**
- Full console output: [Full-log.txt](https://github.com/ColdSpirit0/mod_io_downloader/files/14997971/Full-log.txt)
- Game.ini file: [removed]
(Note that I replaced some things with "censored" because of security reasons. Everything I replaced doesn't contain any special characters though)

**Comment by ColdSpirit0** [comment]
It looks like the problem was related to reading UTF-8 files with the default encoding (cp1252 in your case). The 'wrong' character was an emoji from the modio.json file.

Please update the package by running the command `pip install mod-io-downloader --upgrade` and check how it functions.

**Comment by ColdSpirit0** [comment]
Also, please double-check the Game.ini attachment for any sensitive information. You can remove the attachment because I identified the issue

**Comment by NightV402** [comment]
Alright, it's probably some mod I have on the server that has an emoji in the description. Thanks for the fix, seems to be working now. Also I'll remove the Game.ini file from here like you said, just to be safe
